services:
  nlp-app:
    container_name: nlp-app
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
