services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${REBBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${REBBIT_PASSWORD}
    ports:
      - ${REBBIT_PORT}:15672
      - ${AMQP_PORT}:5672